server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_security?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: (3Wl)6jRejJv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    